# @package _global_
agent:
  pre_action_flow:
    _target_: agent.commands.hyperopt_custom_commands.HyperOpt
    summarize_code_prompt_template: 'summarize_code.jinja'
    k_folds_cv_prompt_template: 'k_folds_cv.jinja'
    loop_flow_prompt_template: 'flow_loop_continue.jinja'
    error_instruct_prompt_template: "error_instruction.jinja"
    search_space_prompt_template: 'suggest_search_space.jinja'
    reflection_strategy: ${task.reflection_strategy}
    bo_steps: 20  # total number of BO steps (divisible by max_repetitions)
    bo_batch_size: 1
    bo_search_spaces: 5  # only if reflection strategy is not null
    max_repetitions: 3  # number of retries if there is an error in the suggestion or BO
    max_retries: 5  # number of times to retry for structured output
    use_error_instructions: ${task.use_error_instructions}
  prompt_builder:
    template_paths: [ "hyperopt/" ]
    default_kwargs:
      cot_type: zero_shot
