defaults:
  - _self_

summarize:
  _target_: agent.commands.Summarize
think:
  _target_: agent.commands.Think
  priority: 10
  limit_per_turn: 1
communicate:
  _target_: agent.commands.Communicate
  priority: 10
  limit_per_turn: 1
select_external_action:
  _target_: agent.commands.SelectExternalAction
generate_external_action:
  _target_: agent.commands.GenerateExternalAction
reflect:
  _target_:agent.commands.Reflect
